### ISSUE TITLE
HAL Link change for [Query] 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-middletier#42] opened 2024-03-14 13:51 UTC
**Problem Description:**
Need to change the query: [queryname]. Right now it looks for Works about this concept but we want it to look for Works about this concept or concepts influenced by this concept. [may need to clarify this after we clarify what query name] 

**Expected Behavior/Solution:**
The record of the concept: Personal narratives, German. should show new query information: Works about this concept or concepts influenced by this concept.  [needs to be updated after clarification of query name] 

**Requirements:**
record of concept: Personal narratives, German will contain information of works about a concept/concepts about a concept influenced by this concept.  [needs to be updated after clarification of query name] 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
https://lux-front-tst.collections.yale.edu/view/concept/a5c8f778-5f2b-4226-9dbd-eb10df3979d2

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- https://github.com/project-lux/lux-middletier/issues/41

**Related links:**
Bugherd: https://www.bugherd.com/projects/284041/tasks/2078

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment] 2024-06-24 20:05
@clarkepeterf What is the query name for this issue?

**Comment by clarkepeterf** [comment] 2024-08-21 14:45
@roamye I think this is a dupe of https://github.com/project-lux/lux-middletier/issues/85

**Comment by roamye** [comment] 2024-08-21 14:59
Dupe of https://github.com/project-lux/lux-middletier/issues/85. Propose close.

**Closed** 2024-08-22 15:31 UTC
Labels: propose-close
