### ISSUE TITLE
HAL LINK for Sets on Event Pages

### ISSUE THREAD

**Issue by ar2674** [project-lux/lux-middletier#30] opened 2024-03-05 20:33 UTC
**Problem Description:**
the front end wishes to add missing data to set/collection pages by creating a HAL link that will add information of a  Set to the Event. 

**Expected Behavior/Solution:**
Create a HAL link which returns the following query: 
TBD- dependent on when peter creates the HAL link 

**Requirements:**
Once HAL link is created, Set information will appear under Event. (Please see mock of dependency issue) 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] ~Frontend requirements- TBD~
- [ ] ~Questions~

**UAT/LUX Examples:**
https://lux-front-tst.collections.yale.edu/view/set/664c4aeb-532f-46a2-9db8-4d0b51c73a64 should render information related to https://lux-front-tst.collections.yale.edu/view/activity/ef9bfa8b-1d19-4b44-a004-a5ab75cdf6d7

**Dependencies/Blocks:**
Dependency:  https://github.com/project-lux/lux-frontend/issues/88

**Related Github Issues:**
- https://github.com/project-lux/lux-middletier/issues/40 (new version of issue) 

**Related links:**

~**Wireframe/Mockup:**~
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by ar2674** [comment] 2024-03-05 20:33
@kamerynB Would u be able to help me form this? It is the HAL link issue for 88 https://github.com/project-lux/lux-frontend/issues/88

**Comment by ar2674** [comment] 2024-03-05 21:45
I have formed this the best I could. If any information is missing please let me know or feel free to make changes. Thank you.

**Comment by kamerynB** [comment] 2024-03-06 14:05
@ar2674 Thank you for adding this. I must have missed it.

**Comment by roamye** [comment] 2024-03-21 15:25
closing as dupe of new tix: #40

**Closed by roamye** 2024-03-21 15:25 UTC
